
- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://localhost:3080"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create NLP GNS3 project
      uri:
        url: "{{ gns3_url }}/v2/projects"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          name: "testingforprojname3"
        body_format: json
        status_code: 201
      register: project_result

    - name: Add router1
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "router1",
            "x": 100,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "158704ed-0665-4328-a56b-880b1733b70d",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {"adapter_type": "e1000", "adapters": 10, "console_type": "telnet", "cpus": 1, "hda_disk_image": "OS10-Disk-1.0.0.vmdk", "hda_disk_interface": "sata", "ram": 4096, "qemu_path": "/usr/bin/qemu-system-x86_64", "replicate_network_connection_state": true}
          }
        body_format: json
        status_code: 201

    - name: Add router2
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "router2",
            "x": 160,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "158704ed-0665-4328-a56b-880b1733b70d",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {"adapter_type": "e1000", "adapters": 10, "console_type": "telnet", "cpus": 1, "hda_disk_image": "OS10-Disk-1.0.0.vmdk", "hda_disk_interface": "sata", "ram": 4096, "qemu_path": "/usr/bin/qemu-system-x86_64", "replicate_network_connection_state": true}
          }
        body_format: json
        status_code: 201

    - name: Add switch1
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "switch1",
            "x": 100,
            "y": 160,
            "compute_id": "local",
            "node_type": "ethernet_switch",
            "symbol": ":/symbols/ethernet_switch.svg",
            "template_id": "f36f5b73-5ee1-48e4-b8e4-45e9b8d3f68e"
          }
        body_format: json
        status_code: 201
