
- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://localhost:3080"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create NLP GNS3 project
      uri:
        url: "{{ gns3_url }}/v2/projects"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          name: "nlp_topology_20260401_154352"
        body_format: json
        status_code: 201
      register: project_result

    - name: Add pc1
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc1",
            "x": 100,
            "y": 100,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        status_code: 201

    - name: Add router1
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "router1",
            "x": 160,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "1f4ea555-fe20-488f-a5c4-7ec9947e876d",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {"adapter_type": "e1000", "adapters": 10, "console_type": "telnet", "cpus": 1, "hda_disk_image": "OS10-Disk-1.0.0.vmdk", "hda_disk_interface": "sata", "ram": 4096, "qemu_path": "/bin/qemu-system-x86_64", "replicate_network_connection_state": true}
          }
        body_format: json
        status_code: 201

    - name: Add router2
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "router2",
            "x": 100,
            "y": 160,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "1f4ea555-fe20-488f-a5c4-7ec9947e876d",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {"adapter_type": "e1000", "adapters": 10, "console_type": "telnet", "cpus": 1, "hda_disk_image": "OS10-Disk-1.0.0.vmdk", "hda_disk_interface": "sata", "ram": 4096, "qemu_path": "/bin/qemu-system-x86_64", "replicate_network_connection_state": true}
          }
        body_format: json
        status_code: 201
